In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df=pd.read_csv("StudentAcadamics.csv")

In [ ]:
df

,Roll No.,Name,sub 1,sub2,sub3,sub4,sub5,total marks,percentage,Result
0,1,A,55.0,0.0,58.0,38.0,97.0,248,49.6,FAIL
1,2,B,88.0,48.0,0.0,37.0,94.0,267,53.4,PASS
2,3,C,96.0,75.0,88.0,NaN,41.0,300,60.0,PASS
3,4,D,37.0,NaN,36.0,78.0,44.0,195,39.0,FAIL
4,5,E,75.0,49.0,NaN,74.0,999.0,252,50.4,PASS
5,6,F,NaN,67.0,62.0,65.0,86.0,280,56.0,PASS
6,7,G,43.0,60.0,98.0,57.0,51.0,309,61.8,PASS
7,8,H,54.0,74.0,NaN,60.0,76.0,264,52.8,PASS
8,9,I,54.0,82.0,38.0,45.0,42.0,261,52.2,PASS
9,10,J,85.0,45.0,99.0,NaN,85.0,314,62.8,PASS
10,11,K,75.0,458.0,78.0,78.0,49.0,356,71.2,PASS
11,12,L,57.0,89.0,NaN,90.0,61.0,297,59.4,PASS
12,13,M,84.0,NaN,59.0,95.0,45.0,283,56.6,PASS
13,14,N,90.0,80.0,97.0,55.0,85.0,407,81.4,PASS
14,15,O,92.0,90.0,876.0,70.0,95.0,401,80.2,PASS
15,16,P,87.0,41.0,63.0,53.0,39.0,283,56.6,PASS
16,17,Q,93.0,40.0,NaN,47.0,55.0,235,47.0,FAIL
17,18,R,95.0,54.0,70.0,83.0,-43.0,400,80.0,PASS
18,19,S,59.0,65.0,92.0,95.0,83.0,394,78.8,PASS
19,20,T,69.0,77.0,84.0,44.0,NaN,329,65.8,PASS
20,21,U,333.0,50.0,67.0,50.0,61.0,228,45.6,PASS
21,22,V,51.0,40.0,74.0,48.0,47.0,200,52.0,FAIL
22,23,W,49.0,48.0,73.0,45.0,75.0,290,58.0,PASS
23,24,X,65.0,58.0,-4.0,60.0,50.0,280,56.0,PASS
24,25,Y,40.0,72.0,45.0,73.0,65.0,295,59.0,FAIL
25,26,Z,56.0,76.0,41.0,NaN,43.0,216,43.2,PASS
26,27,AA,490.0,59.0,NaN,67.0,78.0,235,50.6,PASS
27,28,BB,70.0,NaN,NaN,60.0,47.0,177,35.4,PASS
28,29,CC,54.0,45.0,46.0,66.0,61.0,272,55.2,FAIL
29,30,DD,64.0,45.0,44.0,44.0,53.0,250,50.0,PASS

In [ ]:
df.mean()

<ipython-input-5-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

Roll No.        15.500000
sub 1           91.724138
sub2            73.592593
sub3            95.166667
sub4            62.111111
sub5            91.862069
total marks    283.933333
percentage      57.333333
dtype: float64

In [ ]:
df.loc[:,'percentage'].mean()

57.333333333333336

In [ ]:
df.mean(axis=1)[0:4]

<ipython-input-7-6447142f9231>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean(axis=1)[0:4]

0    68.325000
1    73.675000
2    94.714286
3    61.857143
dtype: float64

In [ ]:
df.median()

<ipython-input-8-6d467abf240d>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()

Roll No.        15.5
sub 1           69.0
sub2            59.0
sub3            65.0
sub4            60.0
sub5            61.0
total marks    280.0
percentage      56.0
dtype: float64

In [ ]:
df.loc[:,'percentage'].median()

56.0

In [ ]:
df.median(axis=1)[0:4]

<ipython-input-11-ccd22b6541c9>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median(axis=1)[0:4]

0    52.3
1    50.7
2    75.0
3    39.0
dtype: float64

In [ ]:
df.mode()

,Roll No.,Name,sub 1,sub2,sub3,sub4,sub5,total marks,percentage,Result
0,1,A,54.0,45.0,-4.0,60.0,61.0,235.0,56.0,PASS
1,2,AA,NaN,NaN,0.0,NaN,NaN,280.0,56.6,NaN
2,3,B,NaN,NaN,36.0,NaN,NaN,283.0,NaN,NaN
3,4,BB,NaN,NaN,38.0,NaN,NaN,NaN,NaN,NaN
4,5,C,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN
5,6,CC,NaN,NaN,44.0,NaN,NaN,NaN,NaN,NaN
6,7,D,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN
7,8,DD,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN
8,9,E,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN
9,10,F,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN
10,11,G,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN
11,12,H,NaN,NaN,63.0,NaN,NaN,NaN,NaN,NaN
12,13,I,NaN,NaN,67.0,NaN,NaN,NaN,NaN,NaN
13,14,J,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN
14,15,K,NaN,NaN,73.0,NaN,NaN,NaN,NaN,NaN
15,16,L,NaN,NaN,74.0,NaN,NaN,NaN,NaN,NaN
16,17,M,NaN,NaN,78.0,NaN,NaN,NaN,NaN,NaN
17,18,N,NaN,NaN,84.0,NaN,NaN,NaN,NaN,NaN
18,19,O,NaN,NaN,88.0,NaN,NaN,NaN,NaN,NaN
19,20,P,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN
20,21,Q,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN
21,22,R,NaN,NaN,98.0,NaN,NaN,NaN,NaN,NaN
22,23,S,NaN,NaN,99.0,NaN,NaN,NaN,NaN,NaN
23,24,T,NaN,NaN,876.0,NaN,NaN,NaN,NaN,NaN
24,25,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.loc[:,'percentage'].mode()

0    56.0
1    56.6
Name: percentage, dtype: float64

In [ ]:
df.min()

Roll No.          1
Name              A
sub 1          37.0
sub2            0.0
sub3           -4.0
sub4           37.0
sub5          -43.0
total marks     177
percentage     35.4
Result         FAIL
dtype: object

In [ ]:
df.loc[:,'percentage'].min(skipna = False)

35.4

In [ ]:
df.max()

Roll No.          30
Name               Z
sub 1          490.0
sub2           458.0
sub3           876.0
sub4            95.0
sub5           999.0
total marks      407
percentage      81.4
Result          PASS
dtype: object

In [ ]:
df.loc[:,'percentage'].min(skipna = False)

35.4

In [ ]:
 df.std()

<ipython-input-20-ce97bb7eaef8>:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.std()

Roll No.         8.803408
sub 1           92.724976
sub2            79.229588
sub3           168.567279
sub4            16.930476
sub5           176.527765
total marks     60.898408
percentage      11.705387
dtype: float64

In [ ]:
df.loc[:,'percentage'].std()

11.705387304742333

In [ ]:
df.groupby(['Roll No.'])['percentage'].mean()

Roll No.
1     49.6
2     53.4
3     60.0
4     39.0
5     50.4
6     56.0
7     61.8
8     52.8
9     52.2
10    62.8
11    71.2
12    59.4
13    56.6
14    81.4
15    80.2
16    56.6
17    47.0
18    80.0
19    78.8
20    65.8
21    45.6
22    52.0
23    58.0
24    56.0
25    59.0
26    43.2
27    50.6
28    35.4
29    55.2
30    50.0
Name: percentage, dtype: float64

In [ ]:
df_u=df.rename(columns={'Percentage overall':'percentage'},inplace=False)

In [ ]:
(df_u.groupby(['Roll No.']).percentage.mean())

Roll No.
1     49.6
2     53.4
3     60.0
4     39.0
5     50.4
6     56.0
7     61.8
8     52.8
9     52.2
10    62.8
11    71.2
12    59.4
13    56.6
14    81.4
15    80.2
16    56.6
17    47.0
18    80.0
19    78.8
20    65.8
21    45.6
22    52.0
23    58.0
24    56.0
25    59.0
26    43.2
27    50.6
28    35.4
29    55.2
30    50.0
Name: percentage, dtype: float64

In [ ]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df[['Roll No.']]).toarray())
enc_df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df_encode =df_u.join(enc_df)
df_encode

,Roll No.,Name,sub 1,sub2,sub3,sub4,sub5,total marks,percentage,Result,...,20,21,22,23,24,25,26,27,28,29
0,1,A,55.0,0.0,58.0,38.0,97.0,248,49.6,FAIL,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,B,88.0,48.0,0.0,37.0,94.0,267,53.4,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,C,96.0,75.0,88.0,NaN,41.0,300,60.0,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,D,37.0,NaN,36.0,78.0,44.0,195,39.0,FAIL,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,E,75.0,49.0,NaN,74.0,999.0,252,50.4,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6,F,NaN,67.0,62.0,65.0,86.0,280,56.0,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7,G,43.0,60.0,98.0,57.0,51.0,309,61.8,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8,H,54.0,74.0,NaN,60.0,76.0,264,52.8,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,I,54.0,82.0,38.0,45.0,42.0,261,52.2,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10,J,85.0,45.0,99.0,NaN,85.0,314,62.8,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,11,K,75.0,458.0,78.0,78.0,49.0,356,71.2,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12,L,57.0,89.0,NaN,90.0,61.0,297,59.4,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,13,M,84.0,NaN,59.0,95.0,45.0,283,56.6,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,14,N,90.0,80.0,97.0,55.0,85.0,407,81.4,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,15,O,92.0,90.0,876.0,70.0,95.0,401,80.2,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,16,P,87.0,41.0,63.0,53.0,39.0,283,56.6,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,17,Q,93.0,40.0,NaN,47.0,55.0,235,47.0,FAIL,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,R,95.0,54.0,70.0,83.0,-43.0,400,80.0,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,19,S,59.0,65.0,92.0,95.0,83.0,394,78.8,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,20,T,69.0,77.0,84.0,44.0,NaN,329,65.8,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,21,U,333.0,50.0,67.0,50.0,61.0,228,45.6,PASS,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,22,V,51.0,40.0,74.0,48.0,47.0,200,52.0,FAIL,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,23,W,49.0,48.0,73.0,45.0,75.0,290,58.0,PASS,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,24,X,65.0,58.0,-4.0,60.0,50.0,280,56.0,PASS,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
24,25,Y,40.0,72.0,45.0,73.0,65.0,295,59.0,FAIL,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
25,26,Z,56.0,76.0,41.0,NaN,43.0,216,43.2,PASS,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
26,27,AA,490.0,59.0,NaN,67.0,78.0,235,50.6,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
27,28,BB,70.0,NaN,NaN,60.0,47.0,177,35.4,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
28,29,CC,54.0,45.0,46.0,66.0,61.0,272,55.2,FAIL,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
29,30,DD,64.0,45.0,44.0,44.0,53.0,250,50.0,PASS,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
Iris=pd.read_csv('Iris_Dataset.csv')

In [ ]:
col_names =['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Species']

In [ ]:
irisSet = (Iris['Species']== 'Iris-setosa')

In [ ]:
print('Iris-setosa')

Iris-setosa

In [ ]:
print(Iris[irisSet].describe())

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [ ]:
irisVer = (Iris['Species']== 'Iris-versicolor')

In [ ]:
print('Iris-versicolor')

Iris-versicolor

In [ ]:
print(Iris[irisVer].describe())

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [ ]:
print('Iris-virginica')

Iris-virginica

In [ ]:
print(Iris[irisVer].describe())

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [ ]:
irisVir = (Iris['Species']== 'Iris-virginica')

In [ ]:
print('Iris-virginica')

Iris-virginica

In [ ]:
print(Iris[irisVir].describe())

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000